apiVersion: redhatcop.redhat.io/v1alpha1
kind: GroupConfig
metadata:
  name: portfolio-dev-config
spec:
  labelSelector:
    matchLabels:
      role: dev
  templates:
  - objectTemplate: |
      apiVersion: rbac.authorization.k8s.io/v1
      kind: RoleBinding
      metadata:
        name: edit-{{ .Labels.application }}-{{ .Name }}-dev
        namespace: {{ .Labels.portfolio }}-{{ .Labels.application }}-dev
      roleRef:
        apiGroup: rbac.authorization.k8s.io
        kind: ClusterRole
        name: edit
      subjects:
      - kind: Group
        apiGroup: rbac.authorization.k8s.io
        name: {{ .Name }}
  - objectTemplate: |
      apiVersion: rbac.authorization.k8s.io/v1
      kind: RoleBinding
      metadata:
        name: view-{{ .Labels.application }}-{{ .Name }}-qa
        namespace: {{ .Labels.portfolio }}-{{ .Labels.application }}-qa
      roleRef:
        apiGroup: rbac.authorization.k8s.io
        kind: ClusterRole
        name: view
      subjects:
      - kind: Group
        apiGroup: rbac.authorization.k8s.io
        name: {{ .Name }}
  - objectTemplate: |
      apiVersion: rbac.authorization.k8s.io/v1
      kind: RoleBinding
      metadata:
        name: view-{{ .Labels.application }}-{{ .Name }}-uat
        namespace: {{ .Labels.portfolio }}-{{ .Labels.application }}-uat
      roleRef:
        apiGroup: rbac.authorization.k8s.io
        kind: ClusterRole
        name: view
      subjects:
      - kind: Group
        apiGroup: rbac.authorization.k8s.io
        name: {{ .Name }}