
---
apiVersion: user.openshift.io/v1
kind: User
metadata:
  name: app3-admin
---
apiVersion: user.openshift.io/v1
kind: User
metadata:
  name: app3-dev
---
apiVersion: user.openshift.io/v1
kind: User
metadata:
  name: app3-view